# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template models.py.jinja --
from pydantic import BaseModel

from . import fields, actions
from ._types import FuncType
from ._builder import serialize_base64
from ._compat import PYDANTIC_V2, ConfigDict

if TYPE_CHECKING:
    from .client import Prisma


_PrismaModelT = TypeVar('_PrismaModelT', bound='_PrismaModel')


class _PrismaModel(BaseModel):
    if PYDANTIC_V2:
        model_config: ClassVar[ConfigDict] = ConfigDict(
            use_enum_values=True,
            arbitrary_types_allowed=True,
            populate_by_name=True,
        )
    elif not TYPE_CHECKING:
        from ._compat import BaseConfig

        class Config(BaseConfig):
            use_enum_values: bool = True
            arbitrary_types_allowed: bool = True
            allow_population_by_field_name: bool = True
            json_encoders: Dict[Any, FuncType] = {
                fields.Base64: serialize_base64,
            }

    # TODO: ensure this is required by subclasses
    __prisma_model__: ClassVar[str]


class BaseCompany(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Company']] = 'Company'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CompanyActions[_PrismaModelT]':
        from .client import get_client

        return actions.CompanyActions[_PrismaModelT](client or get_client(), cls)


class BaseAssistantThread(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AssistantThread']] = 'AssistantThread'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AssistantThreadActions[_PrismaModelT]':
        from .client import get_client

        return actions.AssistantThreadActions[_PrismaModelT](client or get_client(), cls)


class BaseAssistantMessage(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AssistantMessage']] = 'AssistantMessage'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AssistantMessageActions[_PrismaModelT]':
        from .client import get_client

        return actions.AssistantMessageActions[_PrismaModelT](client or get_client(), cls)


class BasePlatformOnboardingRelease(_PrismaModel):
    __prisma_model__: ClassVar[Literal['PlatformOnboardingRelease']] = 'PlatformOnboardingRelease'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.PlatformOnboardingReleaseActions[_PrismaModelT]':
        from .client import get_client

        return actions.PlatformOnboardingReleaseActions[_PrismaModelT](client or get_client(), cls)


class BaseOnboardingReleaseItem(_PrismaModel):
    __prisma_model__: ClassVar[Literal['OnboardingReleaseItem']] = 'OnboardingReleaseItem'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.OnboardingReleaseItemActions[_PrismaModelT]':
        from .client import get_client

        return actions.OnboardingReleaseItemActions[_PrismaModelT](client or get_client(), cls)


class BaseUserOnboardingState(_PrismaModel):
    __prisma_model__: ClassVar[Literal['UserOnboardingState']] = 'UserOnboardingState'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserOnboardingStateActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserOnboardingStateActions[_PrismaModelT](client or get_client(), cls)


class BaseUser(_PrismaModel):
    __prisma_model__: ClassVar[Literal['User']] = 'User'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserActions[_PrismaModelT](client or get_client(), cls)


class BaseAuthOtpChallenge(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AuthOtpChallenge']] = 'AuthOtpChallenge'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AuthOtpChallengeActions[_PrismaModelT]':
        from .client import get_client

        return actions.AuthOtpChallengeActions[_PrismaModelT](client or get_client(), cls)


class BaseCompanyMembership(_PrismaModel):
    __prisma_model__: ClassVar[Literal['CompanyMembership']] = 'CompanyMembership'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CompanyMembershipActions[_PrismaModelT]':
        from .client import get_client

        return actions.CompanyMembershipActions[_PrismaModelT](client or get_client(), cls)


class BaseRole(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Role']] = 'Role'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.RoleActions[_PrismaModelT]':
        from .client import get_client

        return actions.RoleActions[_PrismaModelT](client or get_client(), cls)


class BasePermissionDefinition(_PrismaModel):
    __prisma_model__: ClassVar[Literal['PermissionDefinition']] = 'PermissionDefinition'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.PermissionDefinitionActions[_PrismaModelT]':
        from .client import get_client

        return actions.PermissionDefinitionActions[_PrismaModelT](client or get_client(), cls)


class BaseRolePermission(_PrismaModel):
    __prisma_model__: ClassVar[Literal['RolePermission']] = 'RolePermission'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.RolePermissionActions[_PrismaModelT]':
        from .client import get_client

        return actions.RolePermissionActions[_PrismaModelT](client or get_client(), cls)


class BaseMembershipRole(_PrismaModel):
    __prisma_model__: ClassVar[Literal['MembershipRole']] = 'MembershipRole'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.MembershipRoleActions[_PrismaModelT]':
        from .client import get_client

        return actions.MembershipRoleActions[_PrismaModelT](client or get_client(), cls)


class BaseCompanyModuleConfig(_PrismaModel):
    __prisma_model__: ClassVar[Literal['CompanyModuleConfig']] = 'CompanyModuleConfig'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CompanyModuleConfigActions[_PrismaModelT]':
        from .client import get_client

        return actions.CompanyModuleConfigActions[_PrismaModelT](client or get_client(), cls)


class BaseFieldSecurityPolicy(_PrismaModel):
    __prisma_model__: ClassVar[Literal['FieldSecurityPolicy']] = 'FieldSecurityPolicy'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.FieldSecurityPolicyActions[_PrismaModelT]':
        from .client import get_client

        return actions.FieldSecurityPolicyActions[_PrismaModelT](client or get_client(), cls)


class BaseUserDataAssignment(_PrismaModel):
    __prisma_model__: ClassVar[Literal['UserDataAssignment']] = 'UserDataAssignment'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserDataAssignmentActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserDataAssignmentActions[_PrismaModelT](client or get_client(), cls)


class BaseBusinessInformation(_PrismaModel):
    __prisma_model__: ClassVar[Literal['BusinessInformation']] = 'BusinessInformation'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.BusinessInformationActions[_PrismaModelT]':
        from .client import get_client

        return actions.BusinessInformationActions[_PrismaModelT](client or get_client(), cls)


class BaseSmartSettings(_PrismaModel):
    __prisma_model__: ClassVar[Literal['SmartSettings']] = 'SmartSettings'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SmartSettingsActions[_PrismaModelT]':
        from .client import get_client

        return actions.SmartSettingsActions[_PrismaModelT](client or get_client(), cls)


class BaseLockDateSettings(_PrismaModel):
    __prisma_model__: ClassVar[Literal['LockDateSettings']] = 'LockDateSettings'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.LockDateSettingsActions[_PrismaModelT]':
        from .client import get_client

        return actions.LockDateSettingsActions[_PrismaModelT](client or get_client(), cls)


class BaseLockDatePerUser(_PrismaModel):
    __prisma_model__: ClassVar[Literal['LockDatePerUser']] = 'LockDatePerUser'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.LockDatePerUserActions[_PrismaModelT]':
        from .client import get_client

        return actions.LockDatePerUserActions[_PrismaModelT](client or get_client(), cls)


class BaseTaxesYearEndConfig(_PrismaModel):
    __prisma_model__: ClassVar[Literal['TaxesYearEndConfig']] = 'TaxesYearEndConfig'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.TaxesYearEndConfigActions[_PrismaModelT]':
        from .client import get_client

        return actions.TaxesYearEndConfigActions[_PrismaModelT](client or get_client(), cls)


class BaseCoaCategory(_PrismaModel):
    __prisma_model__: ClassVar[Literal['CoaCategory']] = 'CoaCategory'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CoaCategoryActions[_PrismaModelT]':
        from .client import get_client

        return actions.CoaCategoryActions[_PrismaModelT](client or get_client(), cls)


class BaseCoaSection(_PrismaModel):
    __prisma_model__: ClassVar[Literal['CoaSection']] = 'CoaSection'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CoaSectionActions[_PrismaModelT]':
        from .client import get_client

        return actions.CoaSectionActions[_PrismaModelT](client or get_client(), cls)


class BaseNominalAccount(_PrismaModel):
    __prisma_model__: ClassVar[Literal['NominalAccount']] = 'NominalAccount'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.NominalAccountActions[_PrismaModelT]':
        from .client import get_client

        return actions.NominalAccountActions[_PrismaModelT](client or get_client(), cls)


class BaseBankAccount(_PrismaModel):
    __prisma_model__: ClassVar[Literal['BankAccount']] = 'BankAccount'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.BankAccountActions[_PrismaModelT]':
        from .client import get_client

        return actions.BankAccountActions[_PrismaModelT](client or get_client(), cls)


class BaseCustomer(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Customer']] = 'Customer'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CustomerActions[_PrismaModelT]':
        from .client import get_client

        return actions.CustomerActions[_PrismaModelT](client or get_client(), cls)


class BaseSupplier(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Supplier']] = 'Supplier'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SupplierActions[_PrismaModelT]':
        from .client import get_client

        return actions.SupplierActions[_PrismaModelT](client or get_client(), cls)


class BaseProduct(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Product']] = 'Product'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ProductActions[_PrismaModelT]':
        from .client import get_client

        return actions.ProductActions[_PrismaModelT](client or get_client(), cls)


class BaseCompanyModuleEntitlement(_PrismaModel):
    __prisma_model__: ClassVar[Literal['CompanyModuleEntitlement']] = 'CompanyModuleEntitlement'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CompanyModuleEntitlementActions[_PrismaModelT]':
        from .client import get_client

        return actions.CompanyModuleEntitlementActions[_PrismaModelT](client or get_client(), cls)


class BaseCustomFieldDefinition(_PrismaModel):
    __prisma_model__: ClassVar[Literal['CustomFieldDefinition']] = 'CustomFieldDefinition'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CustomFieldDefinitionActions[_PrismaModelT]':
        from .client import get_client

        return actions.CustomFieldDefinitionActions[_PrismaModelT](client or get_client(), cls)


class BaseSubscriptionRecord(_PrismaModel):
    __prisma_model__: ClassVar[Literal['SubscriptionRecord']] = 'SubscriptionRecord'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SubscriptionRecordActions[_PrismaModelT]':
        from .client import get_client

        return actions.SubscriptionRecordActions[_PrismaModelT](client or get_client(), cls)


class BaseProductUom(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ProductUom']] = 'ProductUom'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ProductUomActions[_PrismaModelT]':
        from .client import get_client

        return actions.ProductUomActions[_PrismaModelT](client or get_client(), cls)


class BaseProject(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Project']] = 'Project'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ProjectActions[_PrismaModelT]':
        from .client import get_client

        return actions.ProjectActions[_PrismaModelT](client or get_client(), cls)


class BaseLocation(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Location']] = 'Location'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.LocationActions[_PrismaModelT]':
        from .client import get_client

        return actions.LocationActions[_PrismaModelT](client or get_client(), cls)


class BaseJournal(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Journal']] = 'Journal'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.JournalActions[_PrismaModelT]':
        from .client import get_client

        return actions.JournalActions[_PrismaModelT](client or get_client(), cls)


class BaseJournalLine(_PrismaModel):
    __prisma_model__: ClassVar[Literal['JournalLine']] = 'JournalLine'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.JournalLineActions[_PrismaModelT]':
        from .client import get_client

        return actions.JournalLineActions[_PrismaModelT](client or get_client(), cls)


class BaseSalesInvoice(_PrismaModel):
    __prisma_model__: ClassVar[Literal['SalesInvoice']] = 'SalesInvoice'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SalesInvoiceActions[_PrismaModelT]':
        from .client import get_client

        return actions.SalesInvoiceActions[_PrismaModelT](client or get_client(), cls)


class BaseSalesInvoiceLine(_PrismaModel):
    __prisma_model__: ClassVar[Literal['SalesInvoiceLine']] = 'SalesInvoiceLine'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SalesInvoiceLineActions[_PrismaModelT]':
        from .client import get_client

        return actions.SalesInvoiceLineActions[_PrismaModelT](client or get_client(), cls)


class BaseSupplierBill(_PrismaModel):
    __prisma_model__: ClassVar[Literal['SupplierBill']] = 'SupplierBill'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SupplierBillActions[_PrismaModelT]':
        from .client import get_client

        return actions.SupplierBillActions[_PrismaModelT](client or get_client(), cls)


class BaseSupplierBillLine(_PrismaModel):
    __prisma_model__: ClassVar[Literal['SupplierBillLine']] = 'SupplierBillLine'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SupplierBillLineActions[_PrismaModelT]':
        from .client import get_client

        return actions.SupplierBillLineActions[_PrismaModelT](client or get_client(), cls)


class BaseBankPayment(_PrismaModel):
    __prisma_model__: ClassVar[Literal['BankPayment']] = 'BankPayment'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.BankPaymentActions[_PrismaModelT]':
        from .client import get_client

        return actions.BankPaymentActions[_PrismaModelT](client or get_client(), cls)


class BaseSalesReceipt(_PrismaModel):
    __prisma_model__: ClassVar[Literal['SalesReceipt']] = 'SalesReceipt'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SalesReceiptActions[_PrismaModelT]':
        from .client import get_client

        return actions.SalesReceiptActions[_PrismaModelT](client or get_client(), cls)


class BaseSupplierPayment(_PrismaModel):
    __prisma_model__: ClassVar[Literal['SupplierPayment']] = 'SupplierPayment'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SupplierPaymentActions[_PrismaModelT]':
        from .client import get_client

        return actions.SupplierPaymentActions[_PrismaModelT](client or get_client(), cls)


class BaseSalesReceiptAllocation(_PrismaModel):
    __prisma_model__: ClassVar[Literal['SalesReceiptAllocation']] = 'SalesReceiptAllocation'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SalesReceiptAllocationActions[_PrismaModelT]':
        from .client import get_client

        return actions.SalesReceiptAllocationActions[_PrismaModelT](client or get_client(), cls)


class BaseSupplierPaymentAllocation(_PrismaModel):
    __prisma_model__: ClassVar[Literal['SupplierPaymentAllocation']] = 'SupplierPaymentAllocation'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SupplierPaymentAllocationActions[_PrismaModelT]':
        from .client import get_client

        return actions.SupplierPaymentAllocationActions[_PrismaModelT](client or get_client(), cls)


class BaseCustomerAdvanceReturn(_PrismaModel):
    __prisma_model__: ClassVar[Literal['CustomerAdvanceReturn']] = 'CustomerAdvanceReturn'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CustomerAdvanceReturnActions[_PrismaModelT]':
        from .client import get_client

        return actions.CustomerAdvanceReturnActions[_PrismaModelT](client or get_client(), cls)


class BaseSupplierAdvanceReturn(_PrismaModel):
    __prisma_model__: ClassVar[Literal['SupplierAdvanceReturn']] = 'SupplierAdvanceReturn'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SupplierAdvanceReturnActions[_PrismaModelT]':
        from .client import get_client

        return actions.SupplierAdvanceReturnActions[_PrismaModelT](client or get_client(), cls)


class BaseBankReceipt(_PrismaModel):
    __prisma_model__: ClassVar[Literal['BankReceipt']] = 'BankReceipt'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.BankReceiptActions[_PrismaModelT]':
        from .client import get_client

        return actions.BankReceiptActions[_PrismaModelT](client or get_client(), cls)


class BaseQuotation(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Quotation']] = 'Quotation'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.QuotationActions[_PrismaModelT]':
        from .client import get_client

        return actions.QuotationActions[_PrismaModelT](client or get_client(), cls)


class BaseQuotationLine(_PrismaModel):
    __prisma_model__: ClassVar[Literal['QuotationLine']] = 'QuotationLine'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.QuotationLineActions[_PrismaModelT]':
        from .client import get_client

        return actions.QuotationLineActions[_PrismaModelT](client or get_client(), cls)


class BaseSalesOrder(_PrismaModel):
    __prisma_model__: ClassVar[Literal['SalesOrder']] = 'SalesOrder'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SalesOrderActions[_PrismaModelT]':
        from .client import get_client

        return actions.SalesOrderActions[_PrismaModelT](client or get_client(), cls)


class BaseSalesOrderLine(_PrismaModel):
    __prisma_model__: ClassVar[Literal['SalesOrderLine']] = 'SalesOrderLine'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SalesOrderLineActions[_PrismaModelT]':
        from .client import get_client

        return actions.SalesOrderLineActions[_PrismaModelT](client or get_client(), cls)


class BasePurchaseOrder(_PrismaModel):
    __prisma_model__: ClassVar[Literal['PurchaseOrder']] = 'PurchaseOrder'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.PurchaseOrderActions[_PrismaModelT]':
        from .client import get_client

        return actions.PurchaseOrderActions[_PrismaModelT](client or get_client(), cls)


class BasePurchaseOrderLine(_PrismaModel):
    __prisma_model__: ClassVar[Literal['PurchaseOrderLine']] = 'PurchaseOrderLine'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.PurchaseOrderLineActions[_PrismaModelT]':
        from .client import get_client

        return actions.PurchaseOrderLineActions[_PrismaModelT](client or get_client(), cls)


class BaseSalesCredit(_PrismaModel):
    __prisma_model__: ClassVar[Literal['SalesCredit']] = 'SalesCredit'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SalesCreditActions[_PrismaModelT]':
        from .client import get_client

        return actions.SalesCreditActions[_PrismaModelT](client or get_client(), cls)


class BaseSalesCreditLine(_PrismaModel):
    __prisma_model__: ClassVar[Literal['SalesCreditLine']] = 'SalesCreditLine'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SalesCreditLineActions[_PrismaModelT]':
        from .client import get_client

        return actions.SalesCreditLineActions[_PrismaModelT](client or get_client(), cls)


class BaseSupplierCredit(_PrismaModel):
    __prisma_model__: ClassVar[Literal['SupplierCredit']] = 'SupplierCredit'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SupplierCreditActions[_PrismaModelT]':
        from .client import get_client

        return actions.SupplierCreditActions[_PrismaModelT](client or get_client(), cls)


class BaseSupplierCreditLine(_PrismaModel):
    __prisma_model__: ClassVar[Literal['SupplierCreditLine']] = 'SupplierCreditLine'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SupplierCreditLineActions[_PrismaModelT]':
        from .client import get_client

        return actions.SupplierCreditLineActions[_PrismaModelT](client or get_client(), cls)


class BaseBankTransfer(_PrismaModel):
    __prisma_model__: ClassVar[Literal['BankTransfer']] = 'BankTransfer'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.BankTransferActions[_PrismaModelT]':
        from .client import get_client

        return actions.BankTransferActions[_PrismaModelT](client or get_client(), cls)


class BaseAttachment(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Attachment']] = 'Attachment'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AttachmentActions[_PrismaModelT]':
        from .client import get_client

        return actions.AttachmentActions[_PrismaModelT](client or get_client(), cls)


class BaseDocumentNumberSequence(_PrismaModel):
    __prisma_model__: ClassVar[Literal['DocumentNumberSequence']] = 'DocumentNumberSequence'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.DocumentNumberSequenceActions[_PrismaModelT]':
        from .client import get_client

        return actions.DocumentNumberSequenceActions[_PrismaModelT](client or get_client(), cls)


class BaseImportJob(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ImportJob']] = 'ImportJob'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ImportJobActions[_PrismaModelT]':
        from .client import get_client

        return actions.ImportJobActions[_PrismaModelT](client or get_client(), cls)


class BaseTransactionTemplate(_PrismaModel):
    __prisma_model__: ClassVar[Literal['TransactionTemplate']] = 'TransactionTemplate'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.TransactionTemplateActions[_PrismaModelT]':
        from .client import get_client

        return actions.TransactionTemplateActions[_PrismaModelT](client or get_client(), cls)


class BaseRecurringSchedule(_PrismaModel):
    __prisma_model__: ClassVar[Literal['RecurringSchedule']] = 'RecurringSchedule'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.RecurringScheduleActions[_PrismaModelT]':
        from .client import get_client

        return actions.RecurringScheduleActions[_PrismaModelT](client or get_client(), cls)


class BaseOutboxEvent(_PrismaModel):
    __prisma_model__: ClassVar[Literal['OutboxEvent']] = 'OutboxEvent'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.OutboxEventActions[_PrismaModelT]':
        from .client import get_client

        return actions.OutboxEventActions[_PrismaModelT](client or get_client(), cls)


class BaseReportRun(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ReportRun']] = 'ReportRun'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ReportRunActions[_PrismaModelT]':
        from .client import get_client

        return actions.ReportRunActions[_PrismaModelT](client or get_client(), cls)


class BaseBankReconciliation(_PrismaModel):
    __prisma_model__: ClassVar[Literal['BankReconciliation']] = 'BankReconciliation'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.BankReconciliationActions[_PrismaModelT]':
        from .client import get_client

        return actions.BankReconciliationActions[_PrismaModelT](client or get_client(), cls)


class BaseBankReconciliationItem(_PrismaModel):
    __prisma_model__: ClassVar[Literal['BankReconciliationItem']] = 'BankReconciliationItem'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.BankReconciliationItemActions[_PrismaModelT]':
        from .client import get_client

        return actions.BankReconciliationItemActions[_PrismaModelT](client or get_client(), cls)


class BaseAuditLogEntry(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AuditLogEntry']] = 'AuditLogEntry'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AuditLogEntryActions[_PrismaModelT]':
        from .client import get_client

        return actions.AuditLogEntryActions[_PrismaModelT](client or get_client(), cls)


class BaseApprovalPolicy(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ApprovalPolicy']] = 'ApprovalPolicy'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ApprovalPolicyActions[_PrismaModelT]':
        from .client import get_client

        return actions.ApprovalPolicyActions[_PrismaModelT](client or get_client(), cls)


class BaseApprovalRequest(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ApprovalRequest']] = 'ApprovalRequest'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ApprovalRequestActions[_PrismaModelT]':
        from .client import get_client

        return actions.ApprovalRequestActions[_PrismaModelT](client or get_client(), cls)


class BaseBudget(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Budget']] = 'Budget'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.BudgetActions[_PrismaModelT]':
        from .client import get_client

        return actions.BudgetActions[_PrismaModelT](client or get_client(), cls)


class BaseBudgetLine(_PrismaModel):
    __prisma_model__: ClassVar[Literal['BudgetLine']] = 'BudgetLine'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.BudgetLineActions[_PrismaModelT]':
        from .client import get_client

        return actions.BudgetLineActions[_PrismaModelT](client or get_client(), cls)


class BaseStockAdjustment(_PrismaModel):
    __prisma_model__: ClassVar[Literal['StockAdjustment']] = 'StockAdjustment'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.StockAdjustmentActions[_PrismaModelT]':
        from .client import get_client

        return actions.StockAdjustmentActions[_PrismaModelT](client or get_client(), cls)


class BaseStockAdjustmentLine(_PrismaModel):
    __prisma_model__: ClassVar[Literal['StockAdjustmentLine']] = 'StockAdjustmentLine'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.StockAdjustmentLineActions[_PrismaModelT]':
        from .client import get_client

        return actions.StockAdjustmentLineActions[_PrismaModelT](client or get_client(), cls)


class BaseStockTransfer(_PrismaModel):
    __prisma_model__: ClassVar[Literal['StockTransfer']] = 'StockTransfer'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.StockTransferActions[_PrismaModelT]':
        from .client import get_client

        return actions.StockTransferActions[_PrismaModelT](client or get_client(), cls)


class BaseStockTransferLine(_PrismaModel):
    __prisma_model__: ClassVar[Literal['StockTransferLine']] = 'StockTransferLine'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.StockTransferLineActions[_PrismaModelT]':
        from .client import get_client

        return actions.StockTransferLineActions[_PrismaModelT](client or get_client(), cls)


class BaseProductBatch(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ProductBatch']] = 'ProductBatch'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ProductBatchActions[_PrismaModelT]':
        from .client import get_client

        return actions.ProductBatchActions[_PrismaModelT](client or get_client(), cls)


class BaseDeliveryNote(_PrismaModel):
    __prisma_model__: ClassVar[Literal['DeliveryNote']] = 'DeliveryNote'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.DeliveryNoteActions[_PrismaModelT]':
        from .client import get_client

        return actions.DeliveryNoteActions[_PrismaModelT](client or get_client(), cls)


class BaseDeliveryNoteLine(_PrismaModel):
    __prisma_model__: ClassVar[Literal['DeliveryNoteLine']] = 'DeliveryNoteLine'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.DeliveryNoteLineActions[_PrismaModelT]':
        from .client import get_client

        return actions.DeliveryNoteLineActions[_PrismaModelT](client or get_client(), cls)


class BaseGoodsReceiptNote(_PrismaModel):
    __prisma_model__: ClassVar[Literal['GoodsReceiptNote']] = 'GoodsReceiptNote'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.GoodsReceiptNoteActions[_PrismaModelT]':
        from .client import get_client

        return actions.GoodsReceiptNoteActions[_PrismaModelT](client or get_client(), cls)


class BaseGoodsReceiptNoteLine(_PrismaModel):
    __prisma_model__: ClassVar[Literal['GoodsReceiptNoteLine']] = 'GoodsReceiptNoteLine'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.GoodsReceiptNoteLineActions[_PrismaModelT]':
        from .client import get_client

        return actions.GoodsReceiptNoteLineActions[_PrismaModelT](client or get_client(), cls)


class BasePostDatedChequeReceived(_PrismaModel):
    __prisma_model__: ClassVar[Literal['PostDatedChequeReceived']] = 'PostDatedChequeReceived'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.PostDatedChequeReceivedActions[_PrismaModelT]':
        from .client import get_client

        return actions.PostDatedChequeReceivedActions[_PrismaModelT](client or get_client(), cls)


class BasePostDatedChequeIssued(_PrismaModel):
    __prisma_model__: ClassVar[Literal['PostDatedChequeIssued']] = 'PostDatedChequeIssued'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.PostDatedChequeIssuedActions[_PrismaModelT]':
        from .client import get_client

        return actions.PostDatedChequeIssuedActions[_PrismaModelT](client or get_client(), cls)


class BaseGoodsIssue(_PrismaModel):
    __prisma_model__: ClassVar[Literal['GoodsIssue']] = 'GoodsIssue'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.GoodsIssueActions[_PrismaModelT]':
        from .client import get_client

        return actions.GoodsIssueActions[_PrismaModelT](client or get_client(), cls)


class BaseGoodsIssueLine(_PrismaModel):
    __prisma_model__: ClassVar[Literal['GoodsIssueLine']] = 'GoodsIssueLine'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.GoodsIssueLineActions[_PrismaModelT]':
        from .client import get_client

        return actions.GoodsIssueLineActions[_PrismaModelT](client or get_client(), cls)


class BaseAssemblyTemplate(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AssemblyTemplate']] = 'AssemblyTemplate'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AssemblyTemplateActions[_PrismaModelT]':
        from .client import get_client

        return actions.AssemblyTemplateActions[_PrismaModelT](client or get_client(), cls)


class BaseAssemblyTemplateLine(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AssemblyTemplateLine']] = 'AssemblyTemplateLine'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AssemblyTemplateLineActions[_PrismaModelT]':
        from .client import get_client

        return actions.AssemblyTemplateLineActions[_PrismaModelT](client or get_client(), cls)


class BaseAssemblyJob(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AssemblyJob']] = 'AssemblyJob'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AssemblyJobActions[_PrismaModelT]':
        from .client import get_client

        return actions.AssemblyJobActions[_PrismaModelT](client or get_client(), cls)


class BaseAssemblyJobLine(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AssemblyJobLine']] = 'AssemblyJobLine'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AssemblyJobLineActions[_PrismaModelT]':
        from .client import get_client

        return actions.AssemblyJobLineActions[_PrismaModelT](client or get_client(), cls)


class BaseFxRevaluationRun(_PrismaModel):
    __prisma_model__: ClassVar[Literal['FxRevaluationRun']] = 'FxRevaluationRun'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.FxRevaluationRunActions[_PrismaModelT]':
        from .client import get_client

        return actions.FxRevaluationRunActions[_PrismaModelT](client or get_client(), cls)


class BaseDigitalInvoiceSubmission(_PrismaModel):
    __prisma_model__: ClassVar[Literal['DigitalInvoiceSubmission']] = 'DigitalInvoiceSubmission'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.DigitalInvoiceSubmissionActions[_PrismaModelT]':
        from .client import get_client

        return actions.DigitalInvoiceSubmissionActions[_PrismaModelT](client or get_client(), cls)


class BasePaymentGatewayTransaction(_PrismaModel):
    __prisma_model__: ClassVar[Literal['PaymentGatewayTransaction']] = 'PaymentGatewayTransaction'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.PaymentGatewayTransactionActions[_PrismaModelT]':
        from .client import get_client

        return actions.PaymentGatewayTransactionActions[_PrismaModelT](client or get_client(), cls)


class BaseDocumentTaxSummary(_PrismaModel):
    __prisma_model__: ClassVar[Literal['DocumentTaxSummary']] = 'DocumentTaxSummary'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.DocumentTaxSummaryActions[_PrismaModelT]':
        from .client import get_client

        return actions.DocumentTaxSummaryActions[_PrismaModelT](client or get_client(), cls)


