from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'Company',
    'AssistantThread',
    'AssistantMessage',
    'PlatformOnboardingRelease',
    'OnboardingReleaseItem',
    'UserOnboardingState',
    'User',
    'AuthOtpChallenge',
    'CompanyMembership',
    'Role',
    'PermissionDefinition',
    'RolePermission',
    'MembershipRole',
    'CompanyModuleConfig',
    'FieldSecurityPolicy',
    'UserDataAssignment',
    'BusinessInformation',
    'SmartSettings',
    'LockDateSettings',
    'LockDatePerUser',
    'TaxesYearEndConfig',
    'CoaCategory',
    'CoaSection',
    'NominalAccount',
    'BankAccount',
    'Customer',
    'Supplier',
    'Product',
    'CompanyModuleEntitlement',
    'CustomFieldDefinition',
    'SubscriptionRecord',
    'ProductUom',
    'Project',
    'Location',
    'Journal',
    'JournalLine',
    'SalesInvoice',
    'SalesInvoiceLine',
    'SupplierBill',
    'SupplierBillLine',
    'BankPayment',
    'SalesReceipt',
    'SupplierPayment',
    'SalesReceiptAllocation',
    'SupplierPaymentAllocation',
    'CustomerAdvanceReturn',
    'SupplierAdvanceReturn',
    'BankReceipt',
    'Quotation',
    'QuotationLine',
    'SalesOrder',
    'SalesOrderLine',
    'PurchaseOrder',
    'PurchaseOrderLine',
    'SalesCredit',
    'SalesCreditLine',
    'SupplierCredit',
    'SupplierCreditLine',
    'BankTransfer',
    'Attachment',
    'DocumentNumberSequence',
    'ImportJob',
    'TransactionTemplate',
    'RecurringSchedule',
    'OutboxEvent',
    'ReportRun',
    'BankReconciliation',
    'BankReconciliationItem',
    'AuditLogEntry',
    'ApprovalPolicy',
    'ApprovalRequest',
    'Budget',
    'BudgetLine',
    'StockAdjustment',
    'StockAdjustmentLine',
    'StockTransfer',
    'StockTransferLine',
    'ProductBatch',
    'DeliveryNote',
    'DeliveryNoteLine',
    'GoodsReceiptNote',
    'GoodsReceiptNoteLine',
    'PostDatedChequeReceived',
    'PostDatedChequeIssued',
    'GoodsIssue',
    'GoodsIssueLine',
    'AssemblyTemplate',
    'AssemblyTemplateLine',
    'AssemblyJob',
    'AssemblyJobLine',
    'FxRevaluationRun',
    'DigitalInvoiceSubmission',
    'PaymentGatewayTransaction',
    'DocumentTaxSummary',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'Company': {
        'memberships': 'CompanyMembership',
        'roles': 'Role',
        'businessInformation': 'BusinessInformation',
        'smartSettings': 'SmartSettings',
        'lockDateSettings': 'LockDateSettings',
        'taxesYearEnd': 'TaxesYearEndConfig',
        'coaCategories': 'CoaCategory',
        'bankAccounts': 'BankAccount',
        'customers': 'Customer',
        'suppliers': 'Supplier',
        'products': 'Product',
        'projects': 'Project',
        'locations': 'Location',
        'journals': 'Journal',
        'attachments': 'Attachment',
        'importJobs': 'ImportJob',
        'auditLogEntries': 'AuditLogEntry',
        'documentSequences': 'DocumentNumberSequence',
        'approvalPolicies': 'ApprovalPolicy',
        'salesInvoices': 'SalesInvoice',
        'supplierBills': 'SupplierBill',
        'bankPayments': 'BankPayment',
        'salesReceipts': 'SalesReceipt',
        'supplierPayments': 'SupplierPayment',
        'bankReceipts': 'BankReceipt',
        'bankTransfers': 'BankTransfer',
        'quotations': 'Quotation',
        'salesOrders': 'SalesOrder',
        'purchaseOrders': 'PurchaseOrder',
        'salesCredits': 'SalesCredit',
        'supplierCredits': 'SupplierCredit',
        'stockAdjustments': 'StockAdjustment',
        'stockTransfers': 'StockTransfer',
        'productBatches': 'ProductBatch',
        'deliveryNotes': 'DeliveryNote',
        'goodsReceiptNotes': 'GoodsReceiptNote',
        'pdcReceived': 'PostDatedChequeReceived',
        'pdcIssued': 'PostDatedChequeIssued',
        'outboxEvents': 'OutboxEvent',
        'reportRuns': 'ReportRun',
        'bankReconciliations': 'BankReconciliation',
        'goodsIssues': 'GoodsIssue',
        'approvalRequests': 'ApprovalRequest',
        'assemblyTemplates': 'AssemblyTemplate',
        'assemblyJobs': 'AssemblyJob',
        'moduleEntitlements': 'CompanyModuleEntitlement',
        'customFieldDefinitions': 'CustomFieldDefinition',
        'subscriptionRecord': 'SubscriptionRecord',
        'fxRevaluationRuns': 'FxRevaluationRun',
        'digitalInvoiceSubmissions': 'DigitalInvoiceSubmission',
        'paymentGatewayTransactions': 'PaymentGatewayTransaction',
        'userOnboardingStates': 'UserOnboardingState',
        'onboardingReleaseItems': 'OnboardingReleaseItem',
        'assistantThreads': 'AssistantThread',
        'budgets': 'Budget',
        'transactionTemplates': 'TransactionTemplate',
        'recurringSchedules': 'RecurringSchedule',
        'customerAdvanceReturns': 'CustomerAdvanceReturn',
        'supplierAdvanceReturns': 'SupplierAdvanceReturn',
        'companyModuleConfigs': 'CompanyModuleConfig',
        'fieldSecurityPolicies': 'FieldSecurityPolicy',
        'userDataAssignments': 'UserDataAssignment',
    },
    'AssistantThread': {
        'company': 'Company',
        'user': 'User',
        'messages': 'AssistantMessage',
    },
    'AssistantMessage': {
        'thread': 'AssistantThread',
    },
    'PlatformOnboardingRelease': {
    },
    'OnboardingReleaseItem': {
        'company': 'Company',
    },
    'UserOnboardingState': {
        'company': 'Company',
        'user': 'User',
    },
    'User': {
        'memberships': 'CompanyMembership',
        'lockDatePerUserRows': 'LockDatePerUser',
        'otpChallenges': 'AuthOtpChallenge',
        'onboardingStates': 'UserOnboardingState',
        'assistantThreads': 'AssistantThread',
    },
    'AuthOtpChallenge': {
        'user': 'User',
    },
    'CompanyMembership': {
        'company': 'Company',
        'user': 'User',
        'role': 'Role',
        'membershipRoles': 'MembershipRole',
        'dataAssignments': 'UserDataAssignment',
    },
    'Role': {
        'company': 'Company',
        'parentRole': 'Role',
        'childRoles': 'Role',
        'memberships': 'CompanyMembership',
        'membershipRoles': 'MembershipRole',
        'rolePermissions': 'RolePermission',
        'fieldSecurityPolicies': 'FieldSecurityPolicy',
    },
    'PermissionDefinition': {
        'rolePermissions': 'RolePermission',
    },
    'RolePermission': {
        'role': 'Role',
        'permission': 'PermissionDefinition',
    },
    'MembershipRole': {
        'membership': 'CompanyMembership',
        'role': 'Role',
    },
    'CompanyModuleConfig': {
        'company': 'Company',
    },
    'FieldSecurityPolicy': {
        'company': 'Company',
        'role': 'Role',
    },
    'UserDataAssignment': {
        'company': 'Company',
        'membership': 'CompanyMembership',
    },
    'BusinessInformation': {
        'company': 'Company',
    },
    'SmartSettings': {
        'company': 'Company',
    },
    'LockDateSettings': {
        'company': 'Company',
        'perUserExtensions': 'LockDatePerUser',
    },
    'LockDatePerUser': {
        'lockDateSettings': 'LockDateSettings',
        'user': 'User',
    },
    'TaxesYearEndConfig': {
        'company': 'Company',
    },
    'CoaCategory': {
        'company': 'Company',
        'sections': 'CoaSection',
    },
    'CoaSection': {
        'category': 'CoaCategory',
        'nominals': 'NominalAccount',
    },
    'NominalAccount': {
        'section': 'CoaSection',
        'journalLines': 'JournalLine',
    },
    'BankAccount': {
        'company': 'Company',
    },
    'Customer': {
        'company': 'Company',
    },
    'Supplier': {
        'company': 'Company',
    },
    'Product': {
        'company': 'Company',
        'uoms': 'ProductUom',
    },
    'CompanyModuleEntitlement': {
        'company': 'Company',
    },
    'CustomFieldDefinition': {
        'company': 'Company',
    },
    'SubscriptionRecord': {
        'company': 'Company',
    },
    'ProductUom': {
        'product': 'Product',
    },
    'Project': {
        'company': 'Company',
    },
    'Location': {
        'company': 'Company',
    },
    'Journal': {
        'company': 'Company',
        'lines': 'JournalLine',
    },
    'JournalLine': {
        'journal': 'Journal',
        'nominalAccount': 'NominalAccount',
    },
    'SalesInvoice': {
        'company': 'Company',
        'lines': 'SalesInvoiceLine',
        'allocations': 'SalesReceiptAllocation',
    },
    'SalesInvoiceLine': {
        'salesInvoice': 'SalesInvoice',
    },
    'SupplierBill': {
        'company': 'Company',
        'lines': 'SupplierBillLine',
        'allocations': 'SupplierPaymentAllocation',
    },
    'SupplierBillLine': {
        'supplierBill': 'SupplierBill',
    },
    'BankPayment': {
        'company': 'Company',
        'customerAdvanceReturn': 'CustomerAdvanceReturn',
    },
    'SalesReceipt': {
        'company': 'Company',
        'allocations': 'SalesReceiptAllocation',
        'advanceReturns': 'CustomerAdvanceReturn',
    },
    'SupplierPayment': {
        'company': 'Company',
        'allocations': 'SupplierPaymentAllocation',
        'advanceReturns': 'SupplierAdvanceReturn',
    },
    'SalesReceiptAllocation': {
        'salesReceipt': 'SalesReceipt',
        'salesInvoice': 'SalesInvoice',
    },
    'SupplierPaymentAllocation': {
        'supplierPayment': 'SupplierPayment',
        'supplierBill': 'SupplierBill',
    },
    'CustomerAdvanceReturn': {
        'company': 'Company',
        'salesReceipt': 'SalesReceipt',
        'bankPayment': 'BankPayment',
    },
    'SupplierAdvanceReturn': {
        'company': 'Company',
        'supplierPayment': 'SupplierPayment',
        'bankReceipt': 'BankReceipt',
    },
    'BankReceipt': {
        'company': 'Company',
        'supplierAdvanceReturn': 'SupplierAdvanceReturn',
    },
    'Quotation': {
        'company': 'Company',
        'lines': 'QuotationLine',
    },
    'QuotationLine': {
        'quotation': 'Quotation',
    },
    'SalesOrder': {
        'company': 'Company',
        'lines': 'SalesOrderLine',
    },
    'SalesOrderLine': {
        'salesOrder': 'SalesOrder',
    },
    'PurchaseOrder': {
        'company': 'Company',
        'lines': 'PurchaseOrderLine',
    },
    'PurchaseOrderLine': {
        'purchaseOrder': 'PurchaseOrder',
    },
    'SalesCredit': {
        'company': 'Company',
        'lines': 'SalesCreditLine',
    },
    'SalesCreditLine': {
        'salesCredit': 'SalesCredit',
    },
    'SupplierCredit': {
        'company': 'Company',
        'lines': 'SupplierCreditLine',
    },
    'SupplierCreditLine': {
        'supplierCredit': 'SupplierCredit',
    },
    'BankTransfer': {
        'company': 'Company',
    },
    'Attachment': {
        'company': 'Company',
    },
    'DocumentNumberSequence': {
        'company': 'Company',
    },
    'ImportJob': {
        'company': 'Company',
    },
    'TransactionTemplate': {
        'company': 'Company',
    },
    'RecurringSchedule': {
        'company': 'Company',
    },
    'OutboxEvent': {
        'company': 'Company',
    },
    'ReportRun': {
        'company': 'Company',
    },
    'BankReconciliation': {
        'company': 'Company',
        'items': 'BankReconciliationItem',
    },
    'BankReconciliationItem': {
        'reconciliation': 'BankReconciliation',
    },
    'AuditLogEntry': {
        'company': 'Company',
    },
    'ApprovalPolicy': {
        'company': 'Company',
    },
    'ApprovalRequest': {
        'company': 'Company',
    },
    'Budget': {
        'company': 'Company',
        'lines': 'BudgetLine',
    },
    'BudgetLine': {
        'budget': 'Budget',
    },
    'StockAdjustment': {
        'company': 'Company',
        'lines': 'StockAdjustmentLine',
    },
    'StockAdjustmentLine': {
        'stockAdjustment': 'StockAdjustment',
    },
    'StockTransfer': {
        'company': 'Company',
        'lines': 'StockTransferLine',
    },
    'StockTransferLine': {
        'stockTransfer': 'StockTransfer',
    },
    'ProductBatch': {
        'company': 'Company',
    },
    'DeliveryNote': {
        'company': 'Company',
        'lines': 'DeliveryNoteLine',
    },
    'DeliveryNoteLine': {
        'deliveryNote': 'DeliveryNote',
    },
    'GoodsReceiptNote': {
        'company': 'Company',
        'lines': 'GoodsReceiptNoteLine',
    },
    'GoodsReceiptNoteLine': {
        'goodsReceiptNote': 'GoodsReceiptNote',
    },
    'PostDatedChequeReceived': {
        'company': 'Company',
    },
    'PostDatedChequeIssued': {
        'company': 'Company',
    },
    'GoodsIssue': {
        'company': 'Company',
        'lines': 'GoodsIssueLine',
    },
    'GoodsIssueLine': {
        'goodsIssue': 'GoodsIssue',
    },
    'AssemblyTemplate': {
        'company': 'Company',
        'lines': 'AssemblyTemplateLine',
        'jobs': 'AssemblyJob',
    },
    'AssemblyTemplateLine': {
        'template': 'AssemblyTemplate',
    },
    'AssemblyJob': {
        'company': 'Company',
        'template': 'AssemblyTemplate',
        'lines': 'AssemblyJobLine',
    },
    'AssemblyJobLine': {
        'job': 'AssemblyJob',
    },
    'FxRevaluationRun': {
        'company': 'Company',
    },
    'DigitalInvoiceSubmission': {
        'company': 'Company',
    },
    'PaymentGatewayTransaction': {
        'company': 'Company',
    },
    'DocumentTaxSummary': {
    },
}

# fmt: on