import type { TourDefinition } from "@/lib/tour/types";

const DEMO_META = {
  estimatedMinutes: 4,
  priority: 85,
  celebrationMessage: "You just completed a full workflow demo. Try it for real whenever you're ready.",
};

/** Interactive product demos — auto-navigation, sample data, animated guidance. */
export const demoSalesInvoiceTour: TourDefinition = {
  id: "demo.sales-invoice",
  version: 1,
  type: "demo",
  title: "Create a sales invoice",
  module: "sales",
  experience: "interactive",
  personas: ["general", "sales", "admin", "accountant"],
  prerequisites: { completedTours: ["onboard.core"] },
  metadata: {
    ...DEMO_META,
    tagline: "From customer to posted invoice in minutes",
  },
  steps: [
    {
      id: "intro",
      target: { kind: "panel" },
      presentation: "panel",
      content: {
        title: "Let's invoice Acme Trading",
        why: "Sales invoices drive revenue recognition and GST compliance.",
        how: "I'll open Sell → Invoices and walk through a realistic example — no data is saved in this demo.",
        assistantLine: "Want me to show how invoicing works? Follow the guide — I'll navigate for you.",
      },
      action: { type: "none" },
      autoAdvanceMs: 2200,
      skippable: true,
    },
    {
      id: "nav-invoices",
      target: { kind: "tour", id: "nav-sales-invoices" },
      presentation: "spotlight",
      content: {
        title: "Sales invoices live here",
        how: "Watch the sidebar — we're opening **Sell → Invoices**.",
        assistantLine: "Most teams start every sale from this list.",
      },
      enterAction: { type: "sidebarNavigate", href: "/sales/invoices", groupLabel: "Sell" },
      validation: { type: "routeMatch", pathname: "/sales/invoices" },
      autoContinue: true,
      autoContinueDelayMs: 1200,
      cursor: { enabled: true, clickPulse: true },
      demoPreviewId: "invoice-acme",
      placement: "right",
    },
    {
      id: "new-invoice",
      target: { kind: "tour", id: "sales-invoices-new" },
      presentation: "spotlight",
      content: {
        title: "Start a new invoice",
        how: "Next we'll open the invoice form with sample lines filled in conceptually.",
        bestPractice: "Confirm customer payment terms before adding lines.",
        assistantLine: "I'll open the new invoice screen for you.",
      },
      enterAction: { type: "navigate", href: "/sales/invoices/new" },
      validation: { type: "routeMatch", pathname: "/sales/invoices/new" },
      autoContinue: true,
      autoContinueDelayMs: 1400,
      cursor: { enabled: true, clickPulse: true },
      demoPreviewId: "invoice-acme",
      placement: "left",
    },
    {
      id: "header",
      target: { kind: "tour", id: "si-new-header" },
      presentation: "spotlight",
      content: {
        title: "Customer & dates",
        how: "Pick **Acme Trading Co.** and today's date — both are required before save.",
        assistantLine: "Header fields control due dates and tax treatment.",
      },
      demoPreviewId: "invoice-acme",
      ghostFill: "sales-invoice-header",
      placement: "bottom",
      pauseAfterMs: 600,
    },
    {
      id: "lines",
      target: { kind: "tour", id: "si-new-lines" },
      presentation: "spotlight",
      content: {
        title: "Line items & GST",
        how: "Add products or services; GST and totals update live in the summary panel.",
        assistantLine: "This is where revenue and tax amounts are born.",
      },
      demoPreviewId: "invoice-acme",
      ghostFill: "sales-invoice-lines",
      placement: "top",
    },
    {
      id: "save",
      target: { kind: "tour", id: "si-new-save" },
      presentation: "spotlight",
      content: {
        title: "Save & post",
        how: "**Save invoice** creates the document. Posting updates accounts receivable and GST reports.",
        assistantLine: "In practice mode you'd click Save yourself — here we celebrate the flow.",
      },
      placement: "bottom",
      skippable: false,
      autoAdvanceMs: 4500,
    },
  ],
};

export const demoBankReconTour: TourDefinition = {
  id: "demo.bank-recon",
  version: 1,
  type: "demo",
  title: "Bank reconciliation",
  module: "bank",
  experience: "interactive",
  personas: ["general", "accountant", "cfo", "admin"],
  metadata: { ...DEMO_META, tagline: "Match your statement to the books" },
  steps: [
    {
      id: "intro",
      target: { kind: "panel" },
      presentation: "panel",
      content: {
        title: "Reconcile May's statement",
        why: "Reconciliation proves your cash balance is right before month-end close.",
        how: "We'll jump to **Money → Reconciliation** and review sample unmatched items.",
        assistantLine: "Let's reconcile your first bank statement together.",
      },
    },
    {
      id: "nav-recon",
      target: { kind: "tour", id: "nav-bank-reconciliation" },
      presentation: "spotlight",
      content: {
        title: "Open reconciliation",
        how: "I'll navigate to the reconciliation workspace.",
        assistantLine: "This is where deposits and payments meet your ledger.",
      },
      enterAction: {
        type: "sidebarNavigate",
        href: "/bank/reconciliation",
        groupLabel: "Money",
      },
      validation: { type: "routeMatch", pathname: "/bank/reconciliation" },
      cursor: { enabled: true, clickPulse: true },
      demoPreviewId: "bank-recon",
      placement: "right",
    },
    {
      id: "start-session",
      target: { kind: "tour", id: "bank-recon-start" },
      presentation: "spotlight",
      content: {
        title: "Start a session",
        how: "Pick the bank account, statement date, and closing balance from your statement.",
        assistantLine: "I'll pre-fill a sample May statement so you can see the flow.",
      },
      demoPreviewId: "bank-recon",
      ghostFill: "bank-recon-start",
      placement: "bottom",
      pauseAfterMs: 800,
    },
    {
      id: "sessions",
      target: { kind: "tour", id: "bank-reconciliation-header" },
      presentation: "spotlight",
      content: {
        title: "Sessions list",
        how: "Open a session to match lines, or start a new one when a statement arrives.",
        bestPractice: "Reconcile weekly so variances stay small.",
        assistantLine: "In a real close you'd click Start — we're staying in demo mode.",
      },
      demoPreviewId: "bank-recon",
      autoAdvanceMs: 4500,
    },
  ],
};

export const demoBankReceiptTour: TourDefinition = {
  id: "demo.bank-receipt",
  version: 1,
  type: "demo",
  title: "Record a bank receipt",
  module: "bank",
  experience: "interactive",
  personas: ["general", "accountant", "cfo", "admin"],
  metadata: { ...DEMO_META, tagline: "Money in — refunds, capital, other income" },
  steps: [
    {
      id: "intro",
      target: { kind: "panel" },
      presentation: "panel",
      content: {
        title: "Bank receipt",
        why: "Not all deposits are customer payments — sometimes it's capital or other income.",
        how: "We'll open **Money → Receipts in** and fill a sample receipt.",
        assistantLine: "This posts DR bank / CR income or nominal.",
      },
    },
    {
      id: "nav",
      target: { kind: "tour", id: "nav-bank-receipts" },
      presentation: "spotlight",
      enterAction: {
        type: "sidebarNavigate",
        href: "/bank/receipts",
        groupLabel: "Money",
      },
      validation: { type: "routeMatch", pathname: "/bank/receipts" },
      content: {
        title: "Receipts in",
        how: "List of bank deposits recorded in the system.",
        assistantLine: "Opening Money → Receipts in.",
      },
      cursor: { enabled: true, clickPulse: true },
      placement: "right",
    },
    {
      id: "new",
      target: { kind: "tour", id: "bank-receipts-new" },
      presentation: "spotlight",
      enterAction: { type: "navigate", href: "/bank/receipts/new" },
      validation: { type: "routeMatch", pathname: "/bank/receipts/new" },
      content: {
        title: "New bank receipt",
        how: "Amount hits your selected bank account.",
        assistantLine: "Watch the sample fields populate.",
      },
      placement: "left",
    },
    {
      id: "header",
      target: { kind: "tour", id: "br-new-header" },
      presentation: "spotlight",
      content: {
        title: "Receipt details",
        how: "Date, bank account, and amount — optional nominal for GL posting.",
      },
      ghostFill: "bank-receipt-header",
      placement: "bottom",
      autoAdvanceMs: 4200,
    },
  ],
};

export const demoBankPaymentTour: TourDefinition = {
  id: "demo.bank-payment",
  version: 1,
  type: "demo",
  title: "Record a bank payment",
  module: "bank",
  experience: "interactive",
  personas: ["general", "accountant", "cfo", "admin"],
  metadata: { ...DEMO_META, tagline: "Payments out — expenses and transfers" },
  steps: [
    {
      id: "intro",
      target: { kind: "panel" },
      presentation: "panel",
      content: {
        title: "Bank payment",
        why: "Track cash leaving the business outside supplier bill workflows.",
        how: "We'll open **Money → Payments out**.",
        assistantLine: "Use this for expenses, transfers, or one-off payouts.",
      },
    },
    {
      id: "nav",
      target: { kind: "tour", id: "nav-bank-payments" },
      presentation: "spotlight",
      enterAction: {
        type: "sidebarNavigate",
        href: "/bank/payments",
        groupLabel: "Money",
      },
      validation: { type: "routeMatch", pathname: "/bank/payments" },
      content: {
        title: "Payments out",
        how: "Every outbound bank movement is listed here.",
        assistantLine: "Navigating to Payments out.",
      },
      cursor: { enabled: true, clickPulse: true },
      placement: "right",
    },
    {
      id: "new",
      target: { kind: "tour", id: "bank-payments-new" },
      presentation: "spotlight",
      enterAction: { type: "navigate", href: "/bank/payments/new" },
      validation: { type: "routeMatch", pathname: "/bank/payments/new" },
      content: {
        title: "New payment",
        how: "Select bank, date, and amount.",
        assistantLine: "Sample data fills in automatically.",
      },
      placement: "left",
    },
    {
      id: "header",
      target: { kind: "tour", id: "bp-new-header" },
      presentation: "spotlight",
      content: {
        title: "Payment details",
        how: "Posts DR expense nominal / CR bank when you save.",
      },
      ghostFill: "bank-payment-header",
      placement: "bottom",
      autoAdvanceMs: 4200,
    },
  ],
};

export const demoPurchaseBillTour: TourDefinition = {
  id: "demo.purchase-bill",
  version: 1,
  type: "demo",
  title: "Enter a supplier bill",
  module: "purchases",
  experience: "interactive",
  personas: ["general", "procurement", "accountant", "admin"],
  metadata: { ...DEMO_META, tagline: "Record what you owe suppliers" },
  steps: [
    {
      id: "intro",
      target: { kind: "panel" },
      presentation: "panel",
      content: {
        title: "Record a supplier bill",
        why: "Bills accrue expenses and GST credits before you pay.",
        how: "We'll open **Buy → Supplier bills** and the new bill form.",
        assistantLine: "Purchases flow mirrors sales — header, lines, save.",
      },
    },
    {
      id: "nav-bills",
      target: { kind: "tour", id: "nav-purchases-bills" },
      presentation: "spotlight",
      enterAction: {
        type: "sidebarNavigate",
        href: "/purchases/bills",
        groupLabel: "Buy",
      },
      validation: { type: "routeMatch", pathname: "/purchases/bills" },
      content: {
        title: "Supplier bills",
        how: "All open and paid bills appear here.",
        assistantLine: "Opening Buy for you now.",
      },
      cursor: { enabled: true, clickPulse: true },
      demoPreviewId: "supplier-bill",
      placement: "right",
    },
    {
      id: "new-bill",
      target: { kind: "tour", id: "purchase-bills-new" },
      presentation: "spotlight",
      enterAction: { type: "navigate", href: "/purchases/bills/new" },
      validation: { type: "routeMatch", pathname: "/purchases/bills/new" },
      content: {
        title: "New bill form",
        how: "Select **Nova Supplies**, add lines, and review totals before save.",
        assistantLine: "Inventory purchases can update stock on post.",
      },
      demoPreviewId: "supplier-bill",
      placement: "left",
    },
    {
      id: "header",
      target: { kind: "tour", id: "bill-new-header" },
      presentation: "spotlight",
      content: {
        title: "Bill header",
        how: "Supplier and bill date drive payment terms and GST.",
      },
      demoPreviewId: "supplier-bill",
      ghostFill: "purchase-bill-header",
      placement: "bottom",
    },
    {
      id: "lines",
      target: { kind: "tour", id: "bill-new-lines" },
      presentation: "spotlight",
      content: {
        title: "Line items",
        how: "Add stock or expense lines; totals update in the summary.",
        assistantLine: "Watch the sample lines appear — demo only.",
      },
      demoPreviewId: "supplier-bill",
      ghostFill: "purchase-bill-lines",
      placement: "top",
    },
  ],
};

export const demoInventoryAdjustTour: TourDefinition = {
  id: "demo.inventory-adjust",
  version: 1,
  type: "demo",
  title: "Inventory adjustment",
  module: "inventory",
  experience: "interactive",
  personas: ["general", "inventory_manager", "admin"],
  metadata: { ...DEMO_META, tagline: "Correct on-hand quantities safely" },
  steps: [
    {
      id: "intro",
      target: { kind: "panel" },
      presentation: "panel",
      content: {
        title: "Adjust stock on hand",
        why: "Cycle counts often differ from system qty — adjustments fix valuation.",
        how: "We'll open **Stock → Stock adjustment**.",
        assistantLine: "Here's how inventory affects accounting.",
      },
    },
    {
      id: "nav-adjust",
      target: { kind: "tour", id: "nav-inventory-stock-adjustment" },
      presentation: "spotlight",
      enterAction: {
        type: "sidebarNavigate",
        href: "/inventory/stock-adjustment",
        groupLabel: "Stock",
      },
      validation: { type: "routeMatch", pathname: "/inventory/stock-adjustment" },
      content: {
        title: "Stock adjustment",
        how: "Create an adjustment document when counts don't match.",
        assistantLine: "Moving to Stock now.",
      },
      cursor: { enabled: true, clickPulse: true },
      demoPreviewId: "stock-adjust",
      placement: "right",
    },
    {
      id: "workspace",
      target: { kind: "tour", id: "main-content" },
      presentation: "spotlight",
      content: {
        title: "Apply the adjustment",
        how: "Enter counted qty; the system proposes the delta and GL impact.",
        bestPractice: "Attach a count sheet reference in notes for auditors.",
      },
      demoPreviewId: "stock-adjust",
      autoAdvanceMs: 4800,
    },
  ],
};

export const demoSupplierPaymentTour: TourDefinition = {
  id: "demo.supplier-payment",
  version: 1,
  type: "demo",
  title: "Pay a supplier",
  module: "purchases",
  experience: "interactive",
  personas: ["general", "procurement", "accountant", "admin"],
  metadata: { ...DEMO_META, tagline: "Settle supplier bills from the bank" },
  steps: [
    {
      id: "intro",
      target: { kind: "panel" },
      presentation: "panel",
      content: {
        title: "Supplier payment",
        why: "Payments reduce AP and move cash out of the bank.",
        how: "We'll open **Buy → Payments** and the payment form.",
        assistantLine: "Similar to customer receipts — header, allocate, save.",
      },
    },
    {
      id: "nav",
      target: { kind: "tour", id: "nav-purchases-payments" },
      presentation: "spotlight",
      enterAction: {
        type: "sidebarNavigate",
        href: "/purchases/payments",
        groupLabel: "Buy",
      },
      validation: { type: "routeMatch", pathname: "/purchases/payments" },
      content: {
        title: "Bill payments",
        how: "Payments linked to supplier bills appear here.",
        assistantLine: "Opening Buy → Payments.",
      },
      cursor: { enabled: true, clickPulse: true },
      placement: "right",
    },
    {
      id: "new",
      target: { kind: "tour", id: "supplier-payments-new" },
      presentation: "spotlight",
      enterAction: { type: "navigate", href: "/purchases/payments/new" },
      validation: { type: "routeMatch", pathname: "/purchases/payments/new" },
      content: {
        title: "New payment",
        how: "Select supplier, bank, and amount.",
        assistantLine: "Sample payment data incoming.",
      },
      placement: "left",
    },
    {
      id: "header",
      target: { kind: "tour", id: "vp-new-header" },
      presentation: "spotlight",
      content: {
        title: "Payment header",
        how: "FIFO can auto-apply to oldest open bills.",
      },
      ghostFill: "supplier-payment-header",
      placement: "bottom",
      autoAdvanceMs: 4000,
    },
  ],
};

export const demoCustomerPaymentTour: TourDefinition = {
  id: "demo.customer-payment",
  version: 1,
  type: "demo",
  title: "Collect a customer payment",
  module: "sales",
  experience: "interactive",
  personas: ["general", "sales", "accountant", "admin"],
  metadata: { ...DEMO_META, tagline: "Allocate receipts to open invoices" },
  steps: [
    {
      id: "intro",
      target: { kind: "panel" },
      presentation: "panel",
      content: {
        title: "Record customer payment",
        why: "Receipts clear AR and update bank balances.",
        how: "We'll open **Sell → Receipts** and the new receipt form.",
        assistantLine: "Let's collect payment against invoice INV-1042.",
      },
    },
    {
      id: "nav-receipts",
      target: { kind: "tour", id: "nav-sales-receipts" },
      presentation: "spotlight",
      enterAction: {
        type: "sidebarNavigate",
        href: "/sales/receipts",
        groupLabel: "Sell",
      },
      validation: { type: "routeMatch", pathname: "/sales/receipts" },
      content: {
        title: "Sales receipts",
        how: "Every customer payment is recorded here.",
        assistantLine: "Opening receipts list.",
      },
      cursor: { enabled: true, clickPulse: true },
      demoPreviewId: "receipt-payment",
      placement: "right",
    },
    {
      id: "new-receipt",
      target: { kind: "tour", id: "sales-receipts-new" },
      presentation: "spotlight",
      enterAction: { type: "navigate", href: "/sales/receipts/new" },
      validation: { type: "routeMatch", pathname: "/sales/receipts/new" },
      content: {
        title: "New receipt",
        how: "Choose customer, amount, and bank account; allocate to open invoices.",
        assistantLine: "Allocation is the magic — it knocks down AR.",
      },
      demoPreviewId: "receipt-payment",
      placement: "left",
    },
    {
      id: "header",
      target: { kind: "tour", id: "sr-new-header" },
      presentation: "spotlight",
      content: {
        title: "Receipt header",
        how: "Customer, bank, and amount — FIFO allocation applies payment to oldest invoices.",
        assistantLine: "Watch sample values appear — nothing is saved in this demo.",
      },
      demoPreviewId: "receipt-payment",
      ghostFill: "sales-receipt-header",
      placement: "bottom",
      pauseAfterMs: 700,
    },
    {
      id: "alloc",
      target: { kind: "tour", id: "sr-new-alloc" },
      presentation: "spotlight",
      content: {
        title: "Allocate to invoices",
        how: "Tick invoices until the receipt is fully applied.",
      },
      demoPreviewId: "receipt-payment",
      placement: "top",
    },
  ],
};

export const demoDashboardTour: TourDefinition = {
  id: "demo.dashboard",
  version: 1,
  type: "demo",
  title: "Dashboard analysis",
  module: "financial",
  experience: "interactive",
  personas: ["general", "cfo", "admin", "accountant"],
  metadata: { ...DEMO_META, tagline: "Read the business pulse in one screen" },
  steps: [
    {
      id: "intro",
      target: { kind: "panel" },
      presentation: "panel",
      content: {
        title: "Your command centre",
        why: "Leaders spot cash, revenue, and risk without running reports first.",
        how: "We'll open **Home → Dashboard** and tour KPI cards.",
        assistantLine: "Let me show how to read this month's story.",
      },
      enterAction: { type: "navigate", href: "/dashboard" },
    },
    {
      id: "header",
      target: { kind: "tour", id: "dashboard-header" },
      presentation: "spotlight",
      validation: { type: "routeMatch", pathname: "/dashboard" },
      content: {
        title: "Business overview",
        how: "Filters and date ranges apply to every widget below.",
        assistantLine: "Start here each morning.",
      },
      demoPreviewId: "dashboard-kpis",
      cursor: { enabled: true },
      placement: "bottom",
    },
    {
      id: "whats-new",
      target: { kind: "tour", id: "dashboard-whats-new" },
      presentation: "spotlight",
      content: {
        title: "What's new",
        how: "Product updates and suggested guides appear here.",
        bestPractice: "Pin tours you repeat monthly for your team.",
      },
      demoPreviewId: "dashboard-kpis",
      autoAdvanceMs: 4200,
    },
  ],
};

export const demoReportsTour: TourDefinition = {
  id: "demo.reports",
  version: 1,
  type: "demo",
  title: "Report generation",
  module: "reports",
  experience: "interactive",
  personas: ["general", "cfo", "accountant", "admin"],
  metadata: { ...DEMO_META, tagline: "From ledger to board-ready PDFs" },
  steps: [
    {
      id: "intro",
      target: { kind: "panel" },
      presentation: "panel",
      content: {
        title: "Generate trusted reports",
        why: "Stakeholders need P&L, balance sheet, and GST figures that tie to the ledger.",
        how: "We'll open **Insights → Reports**.",
        assistantLine: "I'll show favourites and search — fastest path to any report.",
      },
    },
    {
      id: "nav-reports",
      target: { kind: "tour", id: "nav-reports" },
      presentation: "spotlight",
      enterAction: { type: "sidebarNavigate", href: "/reports", groupLabel: "Insights" },
      validation: { type: "routeMatch", pathname: "/reports" },
      content: {
        title: "Reports hub",
        how: "Search, favourites, and categories keep hundreds of reports manageable.",
        assistantLine: "Opening Insights for you.",
      },
      cursor: { enabled: true, clickPulse: true },
      demoPreviewId: "report-pl",
      placement: "right",
    },
    {
      id: "search",
      target: { kind: "tour", id: "reports-hub-search" },
      presentation: "spotlight",
      content: {
        title: "Find any report",
        how: "Type **Profit** to jump to P&L variants instantly.",
      },
      demoPreviewId: "report-pl",
      placement: "bottom",
    },
    {
      id: "favorites",
      target: { kind: "tour", id: "reports-hub-favorites" },
      presentation: "spotlight",
      content: {
        title: "Favourites",
        how: "Pin the five reports you run every close — one click access.",
        bestPractice: "Share favourite sets with your team via learning prefs.",
      },
      demoPreviewId: "report-pl",
      autoAdvanceMs: 4500,
    },
  ],
};

export const demoAssemblyTour: TourDefinition = {
  id: "demo.assembly",
  version: 1,
  type: "demo",
  title: "Assembly / manufacturing job",
  module: "assembly",
  experience: "interactive",
  personas: ["general", "inventory_manager", "admin"],
  metadata: {
    ...DEMO_META,
    tagline: "Build finished goods from components",
  },
  steps: [
    {
      id: "intro",
      target: { kind: "panel" },
      presentation: "panel",
      content: {
        title: "Assembly in Fast Accounts",
        why: "Jobs consume components and absorb labour/overhead into finished goods.",
        how: "We'll tour inventory and how assembly reports tie to the GL.",
        assistantLine: "Think of it as a recipe that moves stock and costs together.",
      },
    },
    {
      id: "nav-products",
      target: { kind: "tour", id: "nav-inventory-products" },
      presentation: "spotlight",
      enterAction: {
        type: "sidebarNavigate",
        href: "/inventory/products",
        groupLabel: "Stock",
      },
      validation: { type: "routeMatch", pathname: "/inventory/products" },
      content: {
        title: "Products & BOMs",
        how: "Finished goods and components are maintained here before jobs run.",
        assistantLine: "Stock module is the foundation for assembly.",
      },
      cursor: { enabled: true, clickPulse: true },
      demoPreviewId: "assembly-job",
      placement: "right",
    },
    {
      id: "concept",
      target: { kind: "tour", id: "main-content" },
      presentation: "spotlight",
      content: {
        title: "Job lifecycle",
        how: "Issue components → record labour → complete job → finished good lands in stock.",
        bestPractice: "Run Assembly Job Cost Summary from Reports after month-end.",
      },
      demoPreviewId: "assembly-job",
      autoAdvanceMs: 5000,
    },
  ],
};

export const ALL_DEMO_TOURS: TourDefinition[] = [
  demoSalesInvoiceTour,
  demoBankReconTour,
  demoBankReceiptTour,
  demoBankPaymentTour,
  demoPurchaseBillTour,
  demoSupplierPaymentTour,
  demoInventoryAdjustTour,
  demoCustomerPaymentTour,
  demoDashboardTour,
  demoReportsTour,
  demoAssemblyTour,
];
