"""Default role templates seeded on company create — RBAC v2."""

from __future__ import annotations

from typing import Any

ROLE_TEMPLATES: list[dict[str, Any]] = [
    {
        "code": "super_admin",
        "name": "Super Admin",
        "description": "Full tenant control including users, roles, and all modules.",
        "sortOrder": 0,
        "permissions": ["*"],
        "isSystem": True,
    },
    {
        "code": "admin",
        "name": "Admin",
        "description": "Manage users, roles, settings, and access all enabled modules.",
        "sortOrder": 1,
        "permissions": [
            "settings.roles.manage",
            "settings.users.invite",
            "settings.users.read",
            "settings.read",
            "settings.access_control.manage",
            "settings.content.manage",
            "sales.*",
            "purchases.*",
            "bank.*",
            "inventory.*",
            "reports.*",
            "settings.journals.create",
            "settings.journals.reverse",
        ],
        "isSystem": True,
    },
    {
        "code": "accountant",
        "name": "Accountant",
        "description": "GL, journals, reports, and bank reconciliation.",
        "sortOrder": 2,
        "permissions": [
            "reports.read",
            "reports.*",
            "settings.journals.create",
            "settings.journals.reverse",
            "bank.read",
            "bank.reconciliation.create",
            "bank.reconciliation.update",
            "bank.reconciliation.complete",
            "bank.payments.create",
            "settings.read",
            "settings.users.read",
            "sales.read",
            "sales.invoices.read",
            "sales.receipts.read",
            "purchases.read",
            "purchases.bills.read",
            "purchases.payments.read",
        ],
        "isSystem": True,
    },
    {
        "code": "sales_manager",
        "name": "Sales Manager",
        "description": "Full sales module including approve and export.",
        "sortOrder": 3,
        "permissions": ["sales.*"],
        "isSystem": True,
    },
    {
        "code": "sales_user",
        "name": "Sales User",
        "description": "Create and edit sales documents without delete or approve.",
        "sortOrder": 4,
        "permissions": [
            "sales.read",
            "sales.customers.read",
            "sales.customers.create",
            "sales.quotations.read",
            "sales.quotations.create",
            "sales.orders.read",
            "sales.orders.create",
            "sales.invoices.read",
            "sales.invoices.create",
            "sales.receipts.read",
            "sales.receipts.create",
            "sales.credits.read",
            "sales.credits.create",
        ],
        "isSystem": True,
    },
    {
        "code": "inventory_manager",
        "name": "Inventory Manager",
        "description": "Full inventory including adjustments and approvals.",
        "sortOrder": 5,
        "permissions": ["inventory.*"],
        "isSystem": True,
    },
    {
        "code": "inventory_user",
        "name": "Inventory User",
        "description": "View and maintain products and transfers.",
        "sortOrder": 6,
        "permissions": [
            "inventory.read",
            "inventory.products.read",
            "inventory.products.create",
            "inventory.adjustments.create",
        ],
        "isSystem": True,
    },
    {
        "code": "procurement_manager",
        "name": "Procurement Manager",
        "description": "Full purchases including approve.",
        "sortOrder": 7,
        "permissions": ["purchases.*"],
        "isSystem": True,
    },
    {
        "code": "procurement_user",
        "name": "Procurement User",
        "description": "Create POs and bills without approve.",
        "sortOrder": 8,
        "permissions": [
            "purchases.read",
            "purchases.suppliers.read",
            "purchases.suppliers.create",
            "purchases.orders.read",
            "purchases.orders.create",
            "purchases.bills.read",
            "purchases.bills.create",
            "purchases.payments.read",
            "purchases.grn.read",
            "purchases.grn.create",
        ],
        "isSystem": True,
    },
    {
        "code": "viewer",
        "name": "Viewer",
        "description": "Read-only access to all enabled modules.",
        "sortOrder": 9,
        "permissions": [
            "sales.read",
            "sales.customers.read",
            "sales.quotations.read",
            "sales.orders.read",
            "sales.invoices.read",
            "sales.receipts.read",
            "sales.credits.read",
            "purchases.read",
            "purchases.suppliers.read",
            "purchases.orders.read",
            "purchases.bills.read",
            "purchases.payments.read",
            "purchases.credits.read",
            "purchases.grn.read",
            "bank.read",
            "inventory.read",
            "inventory.products.read",
            "reports.read",
            "settings.read",
            "settings.users.read",
        ],
        "isSystem": True,
    },
]


def template_by_code(code: str) -> dict[str, Any] | None:
    for tpl in ROLE_TEMPLATES:
        if tpl["code"] == code:
            return tpl
    return None
